import { useSession, signIn, signOut } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Body from "../components/landing/Body";
import SignOutButton from "../components/auth/SignOutButton";

export default function Index() {
  const { data: session } = useSession();
  const router = useRouter();

  if (session) {
    console.log(session);
  }

  const loginOrRedirect = () => {
    if (session) {
      router.push("/demo");
      return;
    }

    signIn();
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {session && <SignOutButton></SignOutButton>}
      <main>
        <Body linkOutOfHome={loginOrRedirect}></Body>
      </main>
    </div>
  );
}
