import Head from "next/head";
import Image from "next/image";
import Title from "../components/landing/Title";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Title></Title>
      </main>

      <footer></footer>
    </div>
  );
}
